plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.0"
    defaultConfig {
        configurations.all {
            resolutionStrategy { force 'androidx.core:core:1.6.0' }
        }
        manifestPlaceholders
        ndk {
            // 设置 SO 库架构，支持 armv7a 和 arm64 架构。 
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }

        packagingOptions {
            pickFirst '**/libc++_shared.so'
        }
        // APPLOG_SCHEME 为必填参数，空缺会造成编译失败。 
        // online 表示直播场景。 

        manifestPlaceholders.put("APPLOG_SCHEME", "online")
        applicationId "com.volcengine.ttsdk.quickstart.demo"
        minSdkVersion 21
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 29
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        pickFirst '**/libc++_shared.so'
        pickFirst '**/libh265enc.so'
        pickFirst '**/libbytenn.so'
    }
//    ndkVersion '16.1.4479499'
}


dependencies {
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.annotation:annotation:1.2.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'commons-net:commons-net:3.6'
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.4.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    // 添加 TTSDK 在线集成地址，推荐使用最新稳定版，获取方式请参考[SDK 下载]章节 

    implementation 'com.bytedanceapi:ttsdk-ttlivepush:1.51.2.6'
    implementation 'com.bytedanceapi:ttsdk-ttlivepull_premium:1.51.2.6'
    implementation ("com.volcengine:VolcEngineRTC:3.58.1.53200")


    api project(path: ':vepicutureinpicture:live')
}
