# Uncomment the next line to define a global platform for your project
source 'https://github.com/volcengine/volcengine-specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
install! 'cocoapods',
         :deterministic_uuids => false,
         :disable_input_output_paths => true
use_modular_headers!
inhibit_all_warnings!

require_relative './screen_capture_extension'
# 是否开启录屏直播能力. 0 关闭 1 开启 
ENV['VE_LIVE_ENABLE_SCREEN_CAPTURE_EXTENSION'] = '1'
velive_enable_extension("#{Pathname.new(__FILE__).dirname}/XCConfig")


target 'VeLiveQuickStartDemo' do
  # 集成推拉流功能 
  pod 'TTSDKFramework', '1.47.1.10-premium', :subspecs => %w[LivePull-RTS LivePush-RTS RTCSDK]
  pod 'TTSDKFramework/ScreenCaptureExtension', '1.47.1.10-premium' if velive_screen_capture_enable?
end

target 'VeLiveQuickStartSCExtension' do
  pod 'TTSDKFramework/ScreenCaptureExtension', '1.47.1.10-premium'
end if velive_screen_capture_enable?

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Fix bundle targets Signing
    if target.respond_to?(:product_type) and target.product_type == 'com.apple.product-type.bundle'
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGN_IDENTITY'] = '-'
        config.build_settings['CODE_SIGN_ENTITLEMENTS'] = '-'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
